### ISSUE TITLE
Czemu

### ISSUE THREAD

**Issue by TheVision6212** [ProgramistaZpolski/no-more-ie#1]
Czemu ty używasz "use strict" w skrypcie który tylko sprawdza useragenta i ewentualnie przekierowuje cię na stronę mozilli? (czemu akurat mozilli???)

**Comment by ProgramistaZpolski** [comment]
1. Use strict jest fajne, powody już kiedyś podawałem.
2. Mozilla to super fundacja 10/10, a firefox to jedyna w zasadzie przyjazna przeciętnemu uzytkownikowi przegladarka która nie jest tworzona przez wielką korporację

**Comment by TheVision6212** [comment]
1. To nie jest jakiś super ultra turbo 2022, który przyśpiesza ci skrypt o 100000000000ms
2. Twoja opinia :)

**Comment by ProgramistaZpolski** [comment]
1. Jestem poprostu przyzwyczajony wszędzie dawać use strict /shrug
2. Ale akurat to że strona działa na IE6 to nie opinia

**Comment by ProgramistaZpolski** [comment]
Mam zamknąć już, czy jeszcze jakieś pytania?

**Comment by chickeeen** [comment]
a twoj stary dusi matke firaną z pepco
> a firefox to jedyna w zasadzie przyjazna przeciętnemu uzytkownikowi przegladarka która nie jest tworzona przez wielką korporację. Also strona mozilli działa na IE6 a my tu redirectujemy użytkowników IE6
są inne przeglądarki przyjazne użytkownikom, a wydaje mi się, że ich strony też działają na IE6
mógłbyś dać użytkownikom strefe wyboru, a nie narzucasz im przeglądarkę
